### PR TITLE
laziness flag & lazy pattern

### PR DESCRIPTION
**Pull request by kakkun61**

### CODE REVIEW

**Comment by takenobu-hs** [comment]
Thanks kakkun, I'll merge and tweak this.

**Comment by takenobu-hs** [comment]
I'll unify "lazy pattern" to "irrefutable pattern".

**Comment by kakkun61** [comment]
This is not an irrefutable pattern.

It can be a lazy and also irrefutable pattern with double tilde.

> Turning patterns into irrefutable ones requires `~(~p)` when `Strict` is enabled.

**Comment by takenobu-hs** [comment]
Thanks for your explanation!
I'll correct with your original PR.

**Pull request merged**
